# Generated by Django 2.2 on 2019-04-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationProfile',
        ),
    ]
